services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: bitcoinuser
      POSTGRES_PASSWORD: bitcoinpass
      POSTGRES_DB: bitcoin_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bitcoinuser"]
      interval: 10s
      retries: 5

  fetcher:
    build:
      context: ./data_fetcher
    environment:
      DB_HOST: postgres
      DB_NAME: bitcoin_db
      DB_USER: bitcoinuser
      DB_PASS: bitcoinpass
    depends_on:
      postgres:
        condition: service_healthy

  airflow:
    build:
      context: ./airflow
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
